"""Type definitions for FRC simulation."""

from .enums import (
    MatchPhase,
    BallState,
    RobotActionType,
    ZoneType,
    ShiftParity,
    Alliance,
)
from .schemas import (
    Position,
    BallVelocity,
    ZoneModifiers,
    ZoneDefinition,
    BallSpawnPoint,
    ScoringTarget,
    FieldConfig,
    RobotConfig,
    RobotAction,
    RobotState,
    BallData,
    AllianceScore,
    Score,
    PhaseTiming,
    GameRules,
    BallPhysicsConfig,
    GameState,
    WSMessage,
    ConfigMessage,
)

__all__ = [
    # Enums
    "MatchPhase",
    "BallState",
    "RobotActionType",
    "ZoneType",
    "ShiftParity",
    "Alliance",
    # Schemas
    "Position",
    "BallVelocity",
    "ZoneModifiers",
    "ZoneDefinition",
    "BallSpawnPoint",
    "ScoringTarget",
    "FieldConfig",
    "RobotConfig",
    "RobotAction",
    "RobotState",
    "BallData",
    "AllianceScore",
    "Score",
    "PhaseTiming",
    "GameRules",
    "BallPhysicsConfig",
    "GameState",
    "WSMessage",
    "ConfigMessage",
]
